version: '3.8'

services:
  ml-pipeline:
    build: .
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: python main.py
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "test", "-f", "/app/main.py"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s